### ISSUE TITLE
Privacy implications for fetching a JSON

### ISSUE THREAD

**Issue by TheFrenchGhosty** [KevinPayravi/indie-wiki-buddy#108]
Hello,

https://github.com/KevinPayravi/indie-wiki-buddy/blob/main/background.js#L54
https://github.com/KevinPayravi/indie-wiki-buddy/blob/main/popup.js#L60
https://github.com/KevinPayravi/indie-wiki-buddy/blob/main/popup.js#L384

The add-on will fetch a JSON, there's no way to opt out, and it's not in the privacy policy: https://getindie.wiki/privacy/

This JSON is currently hosted on GitHub.

There is a privacy implication to that, especially since it does it without telling users about it.

Please, add a way to opt out (and mention it in the privacy policy).

**Comment by KevinPayravi** [comment]
Thanks for the report! I've updated https://getindie.wiki/privacy/ with the following text:

> If the BreezeWiki redirect functionality has been enabled, the extension will pull a list of working BreezeWiki instances from[ a file hosted on GitHub](https://raw.githubusercontent.com/KevinPayravi/breezewiki-instances/main/instances.json), managed by the Indie Wiki Buddy developer. This is done in order to provide the extension with an up-to-date list of working BreezeWiki mirrors.

Does that sound good? Let me know if it needs any more details.

Fetching of the JSON only happens if a user enables BreezeWiki, which is off by default. I don't currently plan to add a more granular opt-out just for the remote fetching. BreezeWiki is included in Indie Wiki Buddy to make it easy to retrieve and switch between a list of working mirrors, as some of them can be rather ephemeral. If a user doesn't want that functionality, I would recommend they use a redirector extension to set up and configure their own redirect to their preferred mirror.

That all being said, I may remove the fetching altogether at some point; extension reviews on the Chrome web store usually only take a day (with exception), so there's limited time savings to managing them via remote JSON.

**Comment by TheFrenchGhosty** [comment]
Good enough. Thanks
