### ISSUE TITLE
Support custom breezewiki redirections

### ISSUE THREAD

**Issue by DeCarabas** [KevinPayravi/indie-wiki-buddy#131]
I host my own breezewiki in order to reduce load on breezewiki.com (and mostly out of habit now). I would love to redirect to my own host, but the set of mirrors is fixed. Would it be possible to allow a custom breezewiki redirect?

(I am currently just using a different extension for redirection.)

**Comment by KevinPayravi** [comment]
@DeCarabas Thanks for the idea! It's possible, but I'm hesitant to do so. I'd like to keep the extension as simple and out-of-the-box as possible. It'd also require giving the extension permission to access all websites, which I'd like to avoid for both user confidence, and avoiding increased scrutiny and review times from the Chrome web store. IMO too much for a feature a very small number of users would use.

I'd recommend continuing to use the separate redirection extension. If you'd like to share your mirror with the public though, I'd be happy to add it to the list of options.

**Comment by Brawl345** [comment]
Would also love this feature. Currently using Redirector but it has a higher priority it seems so it redirects all fandom links to my BreezeWiki instance. But I would like to redirect all wikis that Indie-Wiki-Buddy knows and only the unknown ones to BreezeWiki. E.g. it redirects Pokémon Wiki (Fandom) to my BreezeWiki instance rather than Bulbapedia.

> It'd also require giving the extension permission to access all websites

You can ask for permissions for a specific website at runtime. I did this with my own add-on FreshRSS-Checker here, you can take a look: https://github.com/Brawl345/FreshRSS-Checker/blob/d0e4d03c7aab9a3016d5ecbd0e623a099da0e825/source/options.js#L93-L106  
Manifest v3 is a bit buggy in that aspect though as I still needed to add `"host_permissions": ["http://*/*", "https://*/*"]` even though it's unused. Don't know if that changed.

**Comment by KevinPayravi** [comment]
@Brawl345 I'm re-visiting this issue and just saw your comment, sorry I missed it! I'll look into asking for permissions at runtime - I'd be happy to add custom BreezeWiki instances if I can get it to work with manifest v3 without having that broad host_permissions.

**Comment by KevinPayravi** [comment]
Got it working! Will be included in the next update. I'll update this issue once it's released.

<img width="564" alt="Screenshot of Indie Wiki Buddy's BreezeWiki setting set to a custom domain name" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/c9a0368a-dbf0-4946-aa2f-73b4efabfda8">

----

@Brawl345 I was able to get it working in MV3 with `"optional_host_permissions": ["https://*/*"]`. Thanks again for sharing the `chrome.permissions` API.

**Comment by Brawl345** [comment]
Wohoo, thank you very much! :D

**Comment by Brawl345** [comment]
Works perfectly, thank you!
