### ISSUE TITLE
Access to browsing history?

### ISSUE THREAD

**Issue by frozenpandaman** [KevinPayravi/indie-wiki-buddy#144]
Hi, why does the extension need access to browser history? Thanks.

<img width="431" alt="image" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7245874/59fb8305-6952-4c40-8e91-9ddf304a9f7f">

**Comment by KevinPayravi** [comment]
Hi @frozenpandaman -- Indie Wiki Buddy doesn't have access to your past browsing history, it would need the `history` permission to do that. The "read your browsing history" warning comes from using the `webNavigation` permission, which is used to monitor your web traffic as you go (you could say it has access to your "future history"). See [the permission warnings documentation](https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#permissions_with_warnings) for the full list. It's kind of a confusing warning and has sparked [plenty of discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=429185). 

Indie Wiki Buddy uses `webNavigation` to monitor what webpages you're visiting so that it can redirect you to independent wikis or BreezeWiki. It doesn't store or transmit anything you do.

**Comment by frozenpandaman** [comment]
Thanks for the clarification @KevinPayravi! Sounds like a misleadingly-named thing, but just wanted to check & that makes sense.
