### ISSUE TITLE
bloodborne-wiki.com eligible?

### ISSUE THREAD

**Issue by CommandoGrandma** [KevinPayravi/indie-wiki-buddy#17]
Uncertain how well this would gel with the goals of Indie Wiki Buddy but I figure it's worth pitching.

The main wiki that pops up when you google "Bloodborne Wiki" is the Fextralife wiki (https://bloodborne.wiki.fextralife.com/Bloodborne+Wiki). It's not great; the information quality is lacking, the site UI is clunky, and Fextralife is essentially a wikifarm. They run a network of wikis which seem to exist chiefly for the sake of inflating the viewcount of the operators' Twitch stream, which is embedded on every page.

The site that I would suggest to replace it, https://www.bloodborne-wiki.com, is not _technically_ a wiki; the site's administrator, Meph, maintains the site alone and does all edits personally. However, Meph is pretty plugged into the community, and routinely adds new information on request, with lots of parts of the site being guides, charts, etc. written by attributed community members. The site is vastly more popular within the community than the Fextralife one; it has much more information than the Fextralife one, including a large repository of TCRF style pre-release information and material from supplements like the artbook, and the information is very accurate, mostly being collated from reliable sources like datamining, in-game testing, and official published material. Meph's site is also fully independent, being paid for by donations and out of Meph's own pocket.

I totally understand if the lack of direct user edits disqualifies bloodborne-wiki.com from Indie Wiki Buddy inclusion, but I think it's at least worth considering. Compared to the Fextralife wiki, it certainly feels more like a community wiki, and it's a vastly superior informational site.

**Comment by KevinPayravi** [comment]
Thanks for the submission and details!

This is a tough one, because it definitely looks like a great site that I'd love to point people towards. That being said, I'm wary of expanding the extension's scope to non-wikis, as it can cause difficulties down the line with inclusion criteria, competing fan sites, and users having unclear expectations of where they'll end up.

On the technical side, another challenge is that bloodborne-wiki.com doesn't have consistent paths for content pages (e.g. `/2015/04/executioners.html` vs `/2015/03/saw-spear.html` vs. `/p/covenants.html`). So I believe we could only point people to the homepage, or perhaps the [search page](https://www.bloodborne-wiki.com/search?q=covenants) -- which isn't terrible, just not an ideal or consistent experience.

So at the moment I'm inclined to say no, but I'll keep this in the back of my mind for how we could potentially support quality "almost-wikis" in the future, once the extension is more developed and stable.

I'll leave this open for now in case anyone has ideas to share.
