### ISSUE TITLE
Suggestion: Option to deboost Fandom in search results

### ISSUE THREAD

**Issue by PencilVoid** [KevinPayravi/indie-wiki-buddy#237]
I would like an option to deboost Fandom search results rather than hide them completely. This could maybe be implemented by moving all Fandom results a few pages down. Though, I don't know whether this would be possible client-side in every search engine currently supported.

**Comment by KevinPayravi** [comment]
@PencilVoid Thanks for the suggestion! It's an interesting idea, but it's unfortunately not very practical for this extension to do. It'll be exceedingly difficult to maintain the feature across 7 search engines, especially since some search engines change their presentation by browser/mobile/desktop. Even just hiding results has required periodic fixes and adjustments to work consistently.

**Comment by KevinPayravi** [comment]
This is now sort-of done. IWB, by default, now moves independent wikis above Fandom ones in Google search results (with support for almost all other supported search engines coming soon).
