### ISSUE TITLE
UX: individual wiki settings by language

### ISSUE THREAD

**Issue by NotaInutilis** [KevinPayravi/indie-wiki-buddy#263]
The current individual wiki setting manager only allows to display a list of wikis in one language.

For changing the settings of all the wikis, the user has to go through every language option one by one. This is especially annoying when speaking several languages.

Proposed solution: add an option to display wikis in all languages. Replace the "Viewing wikis in:" line by "Filter wikis by language:".

**Comment by KevinPayravi** [comment]
Good idea - that has always bugged me and I wasn't sure about the best way to approach it, I think the "all language" option could work nicely.

**Comment by NotaInutilis** [comment]
Nice! Another related thought happened: I haven't used the extension for long enough to encounter this but I'm wondering what happens when a wiki is added. Do they default to app settings or user-set ones? Is it necessary to manually configure each new wiki to keep a unified behavior?

**Comment by KevinPayravi** [comment]
> Nice! Another related thought happened: I haven't used the extension for long enough to encounter this but I'm wondering what happens when a wiki is added. Do they default to app settings or user-set ones? Is it necessary to manually configure each new wiki to keep a unified behavior?

Currently, if the user clicks on one of the "set all to X" options, that will become the default for new wikis in that language.

**Comment by NotaInutilis** [comment]
I see. I believe it'd be better to make that setting explicit, by adding an entry saying "Default for new wikis" at the top of the list. I'm not sure it's useful to have a default by language. For the two I use (English and French), I usually want the same filter setting. Granular settings are very good, but I believe most users just want to set one behavior as default for everything and forget about it.

Moreover, as the list is becoming quite long, I'm wondering if a search box can be of use. Sure, ctrl-f exists, but it can't efficiently show all Pokémon wikis in one small list. I think that users might find more useful to apply group settings to a theme rather than a language (all Minecraft wikis rather than all Spanish wikis). So a search box with an "apply X setting to all visible wikis" might have some use cases.

**Comment by KevinPayravi** [comment]
@NotaInutilis Makes sense, I agree with having a global default rather than a default per-language.

I've starting working on this changes, including an "all languages" option.

> adding an entry saying "Default for new wikis" at the top of the list.

Are you thinking of something like this?
<img width="591" alt="Indie Wiki Buddy individual wiki settings" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/215e6177-cc20-4fd4-b4a0-5d456150511a">


With the lock icon, I'm thinking of letting users "lock" the new wiki defaults so that they won't change if they use one of the "change all" buttons. Enabling the lock would do something like highlight the row light-gray and disable the inputs. Or, maybe the "change all" buttons simply won't apply to the new wiki defaults at all. Let me know if you have any thoughts on that!

**Comment by NotaInutilis** [comment]
It was a very good 3.0 release indeed! I'll do some more options and menu nitpicking directly on the HTML file. Do you have any editor to recommend for working on these files? There are a lot of nested divs and I don't want to take too much risks.

**Comment by KevinPayravi** [comment]
@NotaInutilis Thank you! Any and all suggestions welcome.

If you're asking about IDE, I personally use Visual Studio Code, but pretty much any code editor should work. Sublime is also a nice, simple option that can format HTML.

Since the UI is driven by JavaScript, it's best to install the extension locally to test changes. Let me know if I can help with that.

**Comment by KevinPayravi** [comment]
For context when looking back at this issue, here's a screenshot of what the settings look like in `v3.2.0`:
<img width="670" alt="Screenshot 2023-12-15 at 1 02 10 AM" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/279e5930-b5bd-4b2a-bd70-cc487e99fcc8">
