### ISSUE TITLE
Add a wiki: Don't Starve Wiki

### ISSUE THREAD

**Issue by NastyFlytrap** [KevinPayravi/indie-wiki-buddy#305]
Link to origin wiki: https://dontstarve.fandom.com/wiki/Don't_Starve_Wiki
Link to destination (independent) wiki: https://dontstarve.wiki.gg/wiki/Don%27t_Starve_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Indie WIki Buddy doesn't currently include wiki.gg wikis since they aren't really independent. There is a "Redirect to wiki.gg" extension available for [Chrome](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) that can be used alongside Indie Wiki Buddy.

**Comment by NastyFlytrap** [comment]
> Thanks for the submission! Indie WIki Buddy doesn't currently include wiki.gg wikis since they aren't really independent. There is a "Redirect to wiki.gg" extension available for [Chrome](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) that can be used alongside Indie Wiki Buddy.

I understand, but the goals of wiki.gg align and overlap with the goals of wikibuddy
If wiki.gg turns to shit in the future, then you can remove support for it then, but until that point, i suggest not drawing the circle with them outside it
