### ISSUE TITLE
Separate Wiki data from extension

### ISSUE THREAD

**Issue by helloworldSB** [KevinPayravi/indie-wiki-buddy#332]
I suggest separating the data from the code and opening a new repository to store the Wiki data

**Comment by KevinPayravi** [comment]
Going to decline, for now at least. The data structure is tightly coupled with the extension code, and everything in this repo ships together in each release. If the day comes when the extension pulls the data from the web instead of having the data ship in the extension itself, I think that'll be a more compelling reason to split.

Happy to reconsider if there are any specific reasons for splitting the data.
