### ISSUE TITLE
No redirection on brave search

### ISSUE THREAD

**Issue by Henonnnn** [KevinPayravi/indie-wiki-buddy#345]
I'm using Firefox 119.0.1 on Windows with brave search engine but I can't get the wiki redirection to work

**Comment by KevinPayravi** [comment]
Hi @Henonnnn:
* What wiki(s) are you expecting to be redirected in Brave Search but are not?
* Can you share a screenshot of your Indie Wiki Buddy settings?

**Comment by KevinPayravi** [comment]
@Henonnnn By default, Indie Wiki Buddy will keep users within the same language. The French Hollow Knight Wiki doesn't have a redirect because there isn't an independent French wiki. If you want the French versions of wikis to redirect to independent English versions, you can enable the "Redirect non-English Fandom/Fextralife wikis to independent English wikis when no same-language wiki exists" setting.

The French Minecraft wiki redirect has been added to Indie Wiki Buddy, but the Firefox add-ons store has to approve the update first.

**Comment by Henonnnn** [comment]
Ohh ok sorry I was confused because I changed my default search engineI didn't thought of that and normally it's is in English idk why it's not case I haven't even noticed 😅

**Comment by KevinPayravi** [comment]
No worries, thanks for bringing it up! All the various interactions can be confusing.
