### ISSUE TITLE
Add a wiki: Heroes of Might and Magic III Wiki

### ISSUE THREAD

**Issue by Gamerhenky** [KevinPayravi/indie-wiki-buddy#366]
Link to origin wiki: https://heroes-of-might-and-magic.fandom.com
Link to destination (independent) wiki: https://heroes.thelazy.net

**Comment by SnorlaxMonster** [comment]
I found this particular case quite interesting, because the Fandom wiki is being maintained by a bot run by one of the main editors to [heroes.thelazy.net](https://heroes.thelazy.net/), which just copies across pages (not edits) to the Fandom wiki.

Apparently, heroes.thelazy.net is the main wiki site, while the Fandom wiki and [ShoutWiki](https://heroes.shoutwiki.com/) are used as "backups" in case something happens to the independent wiki.

I don't think that very odd arrangement necessarily precludes redirection. But it's certainly an odd situation.

**Comment by KevinPayravi** [comment]
Huh, that is interesting! As long as the thelazy.net wiki is the "source" wiki that everyone is editing, then I think it's a good idea to include in IWB.

**Comment by KevinPayravi** [comment]
Added in `v3.5.0`, now available on both Chrome and Firefox.
