### ISSUE TITLE
Extension requires new permission

### ISSUE THREAD

**Issue by Tiagoquix** [KevinPayravi/indie-wiki-buddy#383]
The new update requires the following permission: `Block content on any page`.

I would like to know why.

Thanks in advance.

**Comment by KevinPayravi** [comment]
Hi @Tiagoquix - the `Block content on any page` permission comes from [declarativeNetRequest](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest), which allows IWB to block or modify network requests in a privacy-friendly way, as `declarativeNetRequest` doesn't provide access to the request content.

`declarativeNetRequest` is used to append an `x-indie-wiki` header whenever you visit BreezeWiki. This header informs BreezeWiki that you have Indie Wiki Buddy enabled, and whether BreezeWiki redirecting is turned on. This is to allow BreezeWiki to customize itself for a better experience (such as hiding their own redirect banners and/or hiding their IWB promotional banners), though these features haven't been implemented by BreezeWiki yet. This is also described in our [privacy policy](https://getindie.wiki/privacy/).

This permission has been in IWB since 2.0.0 for Chrome, but was just added for Firefox in 3.2.0 since they added support for `declarativeNetRequest` earlier this year.

**Comment by eirnym** [comment]
I'd like to opt out of this feature. It's enough for me that I have redirects enabled and I don't want to any plugin to interfere with my traffic and my experience.

**Comment by KevinPayravi** [comment]
As of `v3.4.0`, `declarativeNetRequest` has been removed and IWB no longer appends a header to BreezeWiki requests. See https://github.com/KevinPayravi/indie-wiki-buddy/issues/393#issuecomment-1876744860
