### ISSUE TITLE
make new header setting optional

### ISSUE THREAD

**Issue by eirnym** [KevinPayravi/indie-wiki-buddy#393]
I've read response from https://github.com/KevinPayravi/indie-wiki-buddy/issues/383 and I'd like to opt out from a header to be set.

**Comment by KevinPayravi** [comment]
Thanks for the request.

I've started implementing a toggle (black box is a tooltip that appears when hovering over the question mark):
<img width="408" alt="Indie Wiki Buddy settings, showing a new toggle for having IWB passing a header to BreezeWiki" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/38cc640c-d143-47e8-b52f-18bf1d5997fd">

I may only include this toggle in the full settings page and not the pop-up, as I think it's a niche setting that users would only change once, if ever.

**Comment by eirnym** [comment]
I'd like never to accept filtering permission and still using this plugin. I permit only AD blocker and the only single plugin (strictly required for development) to access filtering capabilities and I don't like the idea to have more plugins using it. Yes, I'm concerned of my personal privacy.

As a developer I have a plugin which modifies headers, but I trust it this is a necessity in that case.

**Comment by KevinPayravi** [comment]
Unfortunately the `declarativeNetRequest` permission cannot be made optional (see [here](https://developer.chrome.com/docs/extensions/reference/api/permissions#step_2_declare_optional_permissions_in_the_manifest)), so the best I can do in that regard is simply not utilize the permission based on the user's setting.

That being said, I've decided to remove the header addition altogether, especially since it's not being used by BreezeWiki at the moment. Indie Wiki Buddy will do any needed modifications to the BreezeWiki DOM itself (like hiding the promotional IWB banner). This change will be in the next update, which should be `v3.4.0`.

**Comment by eirnym** [comment]
@KevinPayravi when extension `3.4.0` will be on Firefox Addons page?

**Comment by KevinPayravi** [comment]
@eirnym The update was submitted to the Firefox store a day ago, and it usually takes a few days for it to be reviewed (I'm guessing by Friday at the latest).
