### ISSUE TITLE
IWB is disabling non-Fandom links in Bing

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#484]
On Desktop, hovering Bing's lightbulb button causes the attached entry to become struck out as if it were a Fandom link, regardless of what the site actually is. The suggested link appears to be whichever link Indie Wiki Buddy inserted first.

For example, I was able to reproduce this with all of the lightbulb buttons on [a Bing search for "Borreload Savage Dragon"](https://www.bing.com/search?q=borreload+savage+dragon). The suggested link is always "Borreload Savage Dragon" on Yugipedia, even though there are several other suggested Yugipedia links (e.g. to "Card Gallery:Borreload Savage Dragon") on the same page.

![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/7100450/1c12d612-7a97-4226-b7c1-04e1a2dec37b)

This issue seems to only occur if Indie Wiki Buddy has removed a Fandom/Fextralife result from the search results.

**Comment by KevinPayravi** [comment]
Thanks for reporting this! Another user reported a related issue, in which a Bulbapedia result was disabled:

<img width="500" alt="Bugged IWB filtering in Bing" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/7ead244a-cce0-412d-b12f-ba6fb0568508">

The underlying issue is that IWB searches the entirety of each search result for Fandom links. On Bing, a single search result can contain many links to many sites, such as in the "Explore further" section. This can lead to a single minor link to Fandom disabling the entire result. That's what we're seeing in both the Borreload and Cresselia examples.

With [this commit](https://github.com/KevinPayravi/indie-wiki-buddy/commit/77d68b0c3edf978e1cd3cf5c1a66136b64dbc5d0), I've made it so that IWB will only check the "top-level" (header) link for Fandom. Links in those "explore further/more" sections should no longer activate IWB. I've also excluded the "Explore further" links from the link-disabling CSS, since those links may be useful to users.

With this change, those smaller Fandom links in the "explore further/more" sections will appear activated. I'll look into disabling those individually.

Here's how the "Borreload Savage Dragon" search looks after this commit:
<img width="500" alt="Fixed IWB filtering in Bing" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/e0815da4-2838-40b5-9a41-fca6d0d88994">
