### ISSUE TITLE
Wrong destination_search_path for Bulbapedia

### ISSUE THREAD

**Issue by Tomelyr** [KevinPayravi/indie-wiki-buddy#581]
Hey,
while searching for a Pokemon, the extension redirected me to 
`https://bulbapedia.bulbagarden.net/wiki/index.php?title=Special:Search&search=Dewgong`
The mod_rewrite tries now to access the page index.php
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/5460892/2d391140-2c2f-44e3-9293-c81d1bbeb52c)
The link without index.php works flawlessly
`https://bulbapedia.bulbagarden.net/wiki/?title=Special:Search&search=Dewgong`

Version 3.5.0, Firefox 123.0, Windows 10

**Comment by KevinPayravi** [comment]
Hi @Tomelyr - this was actually fixed in version 3.6.0 (see [changelog](https://getindie.wiki/changelog/)). You're likely still on 3.5.0 because 3.6.0 requests additional permissions, which you need to approve before Firefox will update the extension. The permissions are:
* Access to `neoseeker.com`, which is a wiki platform we've started redirecting to independent wikis.
* Access to `qwant.com`, `kagi.com`, and several `yandex` domains - these are search engines we're now supporting.
* Access to new BreezeWiki mirrors (which we use to inject redirect banners)
