### ISSUE TITLE
Add a wiki: Manor Lords Wiki (Hooded Horse)

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#669]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://manor-lords.fandom.com
Link to destination (independent) wiki: https://hoodedhorse.com/wiki/Manor_Lords

**Comment by SnorlaxMonster** [comment]
In the past (#479), I had raised an issue with a Hooded Horse wiki because they didn't state a licence (and their Terms of Use implied that they owned the wiki content, like Fextralife does). However, since then, they have updated their site footer to specify that their wikis are all licenced under CC BY-SA 4.0 (and the MediaWiki API also reflects this).

I think it's fine to add Hooded Horse wikis, but we should still tag them as "indie" wikifarms, like we do for wiki.gg and Miraheze.

**Comment by KevinPayravi** [comment]
This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
