### ISSUE TITLE
Embedded video in Google result causes IWB banner to be misplaced

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#758]
When a non-indie Google result includes an embedded video, the IWB banner is placed directly over the top of the original non-indie URL and favicon, instead of above it.

For me, the following occurs on [page 2](https://www.google.com/search?q=mario.fandom.com&start=10) when searching "mario.fandom.com"

![image](https://github.com/user-attachments/assets/4fd8719c-0a56-44fa-9795-6a0969931432)

**Comment by KevinPayravi** [comment]
Thanks for reporting this! Looks like the video results naturally have several more layers of elements, causing IWB to inject the button at a deeper level than it usually does and overlap with the original site title/link (which is absolutely positioned).

I've pushed up commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/a993538e8b297d31e79933829efed626aa379d32 to fix this, by directly doing a CSS query for `div.MjjYud` (the surrounding container for each search result). I typically don't like querying for Google's weird class names since they're subject to change, but this does resolve the issue, and we still fall back on the `closestJsController` and `closestDataDiv` CSS queries when needed.

**Comment by KevinPayravi** [comment]
I ended up having to revert the addition of `div.MjjYud`. The `.MjjYud` class would oftentimes be applied to single results, but sometimes would be applied on a div surrounding _all_ the results on a page. Need to find a better way.

**Comment by KevinPayravi** [comment]
Need to extensively test this, but may be able to get away with moving up one level from the closest `closestJsController`/`closestDataDiv`.

`searchResultContainer = findClosestElement(searchResult, [closestJsController, closestDataDiv]);`
to
`searchResultContainer = findClosestElement(searchResult, [closestJsController, closestDataDiv]).parentNode;`

**Comment by SnorlaxMonster** [comment]
> I ended up having to revert the addition of `div.MjjYud`. The `.MjjYud` class would oftentimes be applied to single results, but sometimes would be applied on a div surrounding _all_ the results on a page. Need to find a better way.

I've poked around in Google's obfuscated class names somewhat recently, and this is surprising to me. Do you have an example of that?

**Comment by SnorlaxMonster** [comment]
Never mind, I looked again, and that appears to be a desktop vs mobile difference. On desktop `.MjjYud` is used on individual result containers, while on mobile it is used on the full list of results.

**Comment by KevinPayravi** [comment]
I do actually see `.MjjYud` on the full list when doing a search on desktop Firefox for [tom nook](https://www.google.com/search?client=firefox-b-d&q=tom+nook):

<img width="1203" alt="Google Search screenshot" src="https://github.com/user-attachments/assets/e63930d6-7145-4b06-8d1e-b6b0ed9ecc7e">

**Comment by KevinPayravi** [comment]
I pushed up a commit (https://github.com/KevinPayravi/indie-wiki-buddy/commit/1affa19c9c5c881b0f5396318b4886d384c8ee82) to use the parent node when hiding or replacing Google search results. The original search result container is still used when re-ordering.

Looks good so far in my testing, but would like to test it a bit more before release. Any help is appreciated!

**Comment by KevinPayravi** [comment]
Released in `v3.9.0`.
