### ISSUE TITLE
Add a wiki: PHIGHTING! Wiki

### ISSUE THREAD

**Issue by xenrelle** [KevinPayravi/indie-wiki-buddy#767]
Link to origin wiki: https://phighting.fandom.com/
Link to destination (independent) wiki: https://phighting.miraheze.org/

**Comment by KevinPayravi** [comment]
Hi @xenrelle - PHIGHTING! Wiki has been supported by Indie Wiki Buddy since February (`v3.5.0`). If you're using the extension, please make sure it's up to date (it may be that you need to re-approve the extension's permission requests; `v3.6.0` introduced additional permissions requests for Kagi, Qwant, Yandex, and Neoseeker).

**Comment by xenrelle** [comment]
oh, my bad! thanks for letting me know, I guess I forgot to update it
