### ISSUE TITLE
Changed URL for 100% Orange Juice Wiki

### ISSUE THREAD

**Issue by arisinwonderland** [KevinPayravi/indie-wiki-buddy#801]
When clicking the redirect banner on a page on https://100orangejuice.fandom.com, the banner redirects to `https://orangejuice.wiki/w/?title=Special:Search&search=[page name]`. However, the official 100% Orange Juice Wiki currently has pages indexed under `https://orangejuice.wiki/wiki/[page name]`, so this results in a 403 error. I tested this using the page https://100orangejuice.fandom.com/wiki/Krilalaris.

**Comment by KevinPayravi** [comment]
Thanks for reporting this!

We don't use the content path for those links; we use the `index.php` entry point to perform the search. I see the wiki went through some server maintenance and I'm guessing the `/w/` entrypoint we were using broke or was changed, and it should now be `/w/index.php`. Will have this fixed in the next update!

**Comment by KevinPayravi** [comment]
Fixed in `v3.11.0` (available for Chrome, soon to be available on Firefox).
