### ISSUE TITLE
Add a wiki: Dominion Strategy

### ISSUE THREAD

**Issue by mplewis** [KevinPayravi/indie-wiki-buddy#857]
Link to origin wiki: 
- https://dominionstrategy.miraheze.org/
- https://dominioncg.fandom.com/
- https://dominionstrategy.fandom.com/

Link to destination (independent) wiki: 
- https://wiki.dominionstrategy.com

Hello! My name is Matt. I'm the server admin of the Dominion Strategy Wiki. Our wiki is the home for information on [Dominion](https://wiki.dominionstrategy.com/index.php/Dominion), the deckbuilding board game by Donald X Vaccarino.

We have had problems with clones of our content showing up on the three sites above. The sites above are in various states of disrepair. The content on those sites has been stolen from our wiki without permission, so I'd like to get a redirect up to lead people back to the source of the most up-to-date content.

Our wiki is independently funded by sponsors on Patreon and we put in a lot of work to keep our content available, well-structured, and accurate. Thank you for running Indie Wiki Buddy!

**Comment by KevinPayravi** [comment]
Thank you for the submission! As of `v3.11.0` (available for Chrome, soon to be available on Firefox), IWB redirects from dominioncg.fandom.com to wiki.dominionstrategy.com. We don't currently support redirecting from Miraheze, but I do see that the Miraheze wiki has gone private so hopefully it's defunct and a redirect is no longer needed.

I also didn't add `dominionstrategy.fandom.com` since that wiki seems to have been cleared out, but I notice there is still some activity there, so I'll go ahead and add that as an additional redirect origin in the next update.
