### ISSUE TITLE
Add a wiki: metroid wiki 

### ISSUE THREAD

**Issue by TCaptainPancake** [KevinPayravi/indie-wiki-buddy#914]
Link to origin wiki: https://metroid.fandom.com/wiki/Metroid_Wiki
Link to destination (independent) wiki: https://www.metroidwiki.org/wiki/Main_Page

**Comment by twonfi** [comment]
The indie Metroid Wiki (the NIWA wiki) was previously submitted in issue #45 but was closed due to the content gap in the NIWA wiki compared to the Fandom wiki (Wikitroid).

Special:Statistics table:

| Stat | Wikitroid | NIWA |
| --- | --- | --- |
| Content pages (articles) | **7025** | 1761 |
| All pages (including project pages and redirects) | **58889** | 10265 |
| Files | **25996** | 4174 |
| Edits | **338535** | 78124 |
| Average edits per page | 5.75 | **7.61** |
